version: '3.2'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www/frontend/web
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "8080:443"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    links:
      - postgres
      - redis
    environment:
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "ELASTICSEARCH_HOSTS=elasticsearch:9200"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    links:
      - postgres
      - redis
    environment:
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "ELASTICSEARCH_HOSTS=elasticsearch:9200"
    tty: true
  postgres:
    image: postgres:13.1-alpine
    environment:
      - "POSTGRES_USER=app"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=laravel"
    volumes:
      - ./docker/storage/docker/postgresql:/var/lib/postgresql/data
    ports:
      - "54321:5432"
  redis:
    image: redis
    ports:
      - "63791:6379"
  node:
    build:
      context: ./
      dockerfile: docker/node.docker
    volumes:
      - ./:/var/www
    tty: true


